name: Sample workflow

on:
  issues: 
    types: [opened, edited]

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "An issue was created: $ISSUE_BODY"
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
      - run: |
          # Push the issue to our internal issue tracker
          curl https://trello.com >/dev/null
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}

