name: Sample workflow

on:
  issues: 
    types: [opened]

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "An issue was created: $ISSUE_TITLE"
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          SOME_SECRET: ${{ secrets.SOME_SECRET }}

