name: Sample workflow

on:
  issues: 
    types: [opened]

jobs:
  do-work:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "An issue was created: $ISSUE_TITLE"
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
      - run: |
          # Push the issue to our internal issue tracker
          curl https://trello.com
        env:
          TRELLO_KEY: ${{ secrets.TRELLO_KEY }}

